// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
)

type User struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	Password    sql.NullString `json:"password"`
	WxPusherUID sql.NullString `json:"wxPusherUid"`
	Admin       bool           `json:"admin"`
}
