// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: panels.sql

package queries

import (
	"context"
)

const createPanel = `-- name: CreatePanel :one
;

INSERT INTO panels (name, url, client_id, client_secret)
VALUES (?, ?, ?, ?)
RETURNING id, created_at, updated_at, name, url, client_id, client_secret
`

type CreatePanelParams struct {
	Name         string `json:"name"`
	Url          string `json:"url"`
	ClientID     string `json:"clientId"`
	ClientSecret string `json:"clientSecret"`
}

func (q *Queries) CreatePanel(ctx context.Context, arg CreatePanelParams) (*Panel, error) {
	row := q.db.QueryRowContext(ctx, createPanel,
		arg.Name,
		arg.Url,
		arg.ClientID,
		arg.ClientSecret,
	)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.ClientID,
		&i.ClientSecret,
	)
	return &i, err
}

const deletePanelByID = `-- name: DeletePanelByID :exec
DELETE
FROM panels
WHERE id = ?
`

func (q *Queries) DeletePanelByID(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, deletePanelByID, id)
	return err
}

const getPanelByID = `-- name: GetPanelByID :one
SELECT id, created_at, updated_at, name, url, client_id, client_secret
FROM panels
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetPanelByID(ctx context.Context, id int) (*Panel, error) {
	row := q.db.QueryRowContext(ctx, getPanelByID, id)
	var i Panel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.ClientID,
		&i.ClientSecret,
	)
	return &i, err
}

const listPanels = `-- name: ListPanels :many
SELECT id, created_at, updated_at, name, url, client_id, client_secret
FROM panels
ORDER BY id
`

func (q *Queries) ListPanels(ctx context.Context) ([]*Panel, error) {
	rows, err := q.db.QueryContext(ctx, listPanels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Panel
	for rows.Next() {
		var i Panel
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.ClientID,
			&i.ClientSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePanel = `-- name: UpdatePanel :exec
UPDATE panels
SET name          = ?,
    url           = ?,
    client_id     = ?,
    client_secret = ?,
    updated_at    = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePanelParams struct {
	Name         string `json:"name"`
	Url          string `json:"url"`
	ClientID     string `json:"clientId"`
	ClientSecret string `json:"clientSecret"`
	ID           int    `json:"id,string"`
}

func (q *Queries) UpdatePanel(ctx context.Context, arg UpdatePanelParams) error {
	_, err := q.db.ExecContext(ctx, updatePanel,
		arg.Name,
		arg.Url,
		arg.ClientID,
		arg.ClientSecret,
		arg.ID,
	)
	return err
}
