// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package queries

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, wx_pusher_uid)
VALUES (?, ?, ?)
RETURNING id, username, password, wx_pusher_uid, admin
`

type CreateUserParams struct {
	Username    string         `json:"username"`
	Password    sql.NullString `json:"password"`
	WxPusherUID sql.NullString `json:"wxPusherUid"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password, arg.WxPusherUID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.WxPusherUID,
		&i.Admin,
	)
	return &i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password, wx_pusher_uid, admin
FROM users
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.WxPusherUID,
		&i.Admin,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, wx_pusher_uid, admin
FROM users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.WxPusherUID,
		&i.Admin,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password, wx_pusher_uid, admin
FROM users
ORDER BY id
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.WxPusherUID,
			&i.Admin,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username    = ?,
    password    = ?,
    wx_pusher_uid = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Username    string         `json:"username"`
	Password    sql.NullString `json:"password"`
	WxPusherUID sql.NullString `json:"wxPusherUid"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Password,
		arg.WxPusherUID,
		arg.ID,
	)
	return err
}
