basePath: /api/v1
definitions:
  apiv1.CreatePanelParams:
    properties:
      clientId:
        maxLength: 128
        minLength: 1
        type: string
      clientSecret:
        maxLength: 128
        minLength: 1
        type: string
      name:
        maxLength: 64
        minLength: 1
        type: string
      url:
        type: string
    required:
    - clientId
    - clientSecret
    - name
    - url
    type: object
  apiv1.UpdatePanelParams:
    properties:
      clientId:
        maxLength: 128
        minLength: 1
        type: string
      clientSecret:
        maxLength: 128
        minLength: 1
        type: string
      id:
        type: integer
      name:
        maxLength: 64
        minLength: 1
        type: string
      url:
        type: string
    required:
    - clientId
    - clientSecret
    - id
    - name
    - url
    type: object
  httperr.HTTPError:
    properties:
      detail: {}
      message:
        type: string
    type: object
  queries.Panel:
    properties:
      clientId:
        type: string
      clientSecret:
        type: string
      createdAt:
        type: string
      id:
        example: "0"
        type: string
      name:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Qinglong Envs API
  title: Qinglong Envs
  version: "1.0"
paths:
  /panels:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/queries.Panel'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperr.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.HTTPError'
      summary: 获取面板列表
      tags:
      - panel
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建面板
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/apiv1.CreatePanelParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperr.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.HTTPError'
      summary: 创建面板
      tags:
      - panel
    put:
      consumes:
      - application/json
      parameters:
      - description: 创建面板
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/apiv1.UpdatePanelParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/queries.Panel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperr.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.HTTPError'
      summary: 更新面板
      tags:
      - panel
  /panels/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 面板ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperr.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.HTTPError'
      summary: 删除面板
      tags:
      - panel
    get:
      consumes:
      - application/json
      parameters:
      - description: 面板ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/queries.Panel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httperr.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httperr.HTTPError'
      summary: 获取面板
      tags:
      - panel
swagger: "2.0"
